import 'package:flutter/material.dart';
import '../../l10n/app_localizations.dart';

export '../../l10n/app_localizations.dart';

extension AppLocalizationsExtension on BuildContext {
  String tr(String key) {
    final loc = AppLocalizations.of(this);
    if (loc == null) return key;

    switch (key) {
      case 'appTitle':
        return loc.appTitle;
      case 'settings':
        return loc.settings;
      case 'appearance':
        return loc.appearance;
      case 'theme':
        return loc.theme;
      case 'lightTheme':
        return loc.lightTheme;
      case 'darkTheme':
        return loc.darkTheme;
      case 'systemTheme':
        return loc.systemTheme;
      case 'language':
        return loc.language;
      case 'chooseLanguage':
        return loc.chooseLanguage;
      case 'english':
        return loc.english;
      case 'swahili':
        return loc.swahili;
      case 'general':
        return loc.general;
      case 'account':
        return loc.account;
      case 'logout':
        return loc.logout;
      case 'notifications':
        return loc.notifications;
      case 'helpHelp':
        return loc.helpHelp;
      case 'privacyPolicy':
        return loc.privacyPolicy;
      case 'termsOfService':
        return loc.termsOfService;
      case 'dashboard':
        return loc.dashboard;
      case 'home':
        return loc.home;
      case 'myJobs':
        return loc.myJobs;
      case 'chat':
        return loc.chat;
      case 'profile':
        return loc.profile;
      case 'search':
        return loc.search;
      case 'post_job_title':
        return loc.post_job_title;
      case 'job_details_step':
        return loc.job_details_step;
      case 'location_payment_step':
        return loc.location_payment_step;
      case 'fill_job_details':
        return loc.fill_job_details;
      case 'image_picker_camera':
        return loc.image_picker_camera;
      case 'image_picker_gallery':
        return loc.image_picker_gallery;
      case 'add_image_optional':
        return loc.add_image_optional;
      case 'enter_job_title':
        return loc.enter_job_title;
      case 'job_title_error':
        return loc.job_title_error;
      case 'select_category':
        return loc.select_category;
      case 'category_error':
        return loc.category_error;
      case 'your_budget':
        return loc.your_budget;
      case 'budget_error':
        return loc.budget_error;
      case 'budget_invalid':
        return loc.budget_invalid;
      case 'phone_number':
        return loc.phone_number;
      case 'phone_error':
        return loc.phone_error;
      case 'additional_details':
        return loc.additional_details;
      case 'next_step_location':
        return loc.next_step_location;
      case 'choose_location_title':
        return loc.choose_location_title;
      case 'location_description':
        return loc.location_description;
      case 'use_my_location':
        return loc.use_my_location;
      case 'posting_job':
        return loc.posting_job;
      case 'searching_workers':
        return loc.searching_workers;
      case 'go_back':
        return loc.go_back;
      case 'search_post':
        return loc.search_post;
      case 'job_posted_success':
        return loc.job_posted_success;
      case 'job_posted_message':
        return loc.job_posted_message;
      case 'workers_found_title':
        return loc.workers_found_title;
      case 'wait':
        return loc.wait;
      case 'post_job_btn':
        return loc.post_job_btn;
      case 'no_workers_title':
        return loc.no_workers_title;
      case 'no_workers_message':
        return loc.no_workers_message;
      case 'network_error_title':
        return loc.network_error_title;
      case 'network_error_message':
        return loc.network_error_message;
      case 'cancel':
        return loc.cancel;
      case 'post_anyway':
        return loc.post_anyway;
      case 'gps_permission_denied':
        return loc.gps_permission_denied;
      case 'enable_gps':
        return loc.enable_gps;
      case 'how_to_find_worker':
        return loc.how_to_find_worker;
      case 'tips_description':
        return loc.tips_description;
      case 'categories_title':
        return loc.categories_title;
      case 'recent_jobs_title':
        return loc.recent_jobs_title;
      case 'view_all':
        return loc.view_all;
      case 'no_jobs_here':
        return loc.no_jobs_here;
      case 'jobs_will_appear_here':
        return loc.jobs_will_appear_here;
      case 'pending_tab':
        return loc.pending_tab;
      case 'all_tab':
        return loc.all_tab;
      case 'active_tab':
        return loc.active_tab;
      case 'completed_tab':
        return loc.completed_tab;
      case 'retry_payment':
        return loc.retry_payment;
      case 'delete_job':
        return loc.delete_job;
      case 'confirm_delete_job':
        return loc.confirm_delete_job;
      case 'yes_delete':
        return loc.yes_delete;
      case 'no':
        return loc.no;
      case 'job_deleted_success':
        return loc.job_deleted_success;
      case 'payment_initiated':
        return loc.payment_initiated;
      case 'conversations':
        return loc.conversations;
      case 'no_conversations':
        return loc.no_conversations;
      case 'conversations_subtitle':
        return loc.conversations_subtitle;
      case 'edit_profile':
        return loc.edit_profile;
      case 'save_changes':
        return loc.save_changes;
      case 'full_name':
        return loc.full_name;
      case 'enter_name':
        return loc.enter_name;
      case 'profile_updated_success':
        return loc.profile_updated_success;
      case 'user_info_missing':
        return loc.user_info_missing;
      case 'status_completed':
        return loc.status_completed;
      case 'status_assigned':
        return loc.status_assigned;
      case 'status_in_progress':
        return loc.status_in_progress;
      case 'status_active':
        return loc.status_active;
      case 'status_offered':
        return loc.status_offered;
      case 'status_cancelled':
        return loc.status_cancelled;
      case 'status_pending_payment':
        return loc.status_pending_payment;
      case 'status_empty':
        return loc.status_empty;
      case 'location_title':
        return loc.location_title;
      case 'worker_applications':
        return loc.worker_applications;
      case 'no_applications_yet':
        return loc.no_applications_yet;
      case 'wait_for_workers':
        return loc.wait_for_workers;
      case 'assigned_worker':
        return loc.assigned_worker;
      case 'completion_code_title':
        return loc.completion_code_title;
      case 'give_code_instruction':
        return loc.give_code_instruction;
      case 'delete_job_btn':
        return loc.delete_job_btn;
      case 'deleting':
        return loc.deleting;
      case 'call_worker':
        return loc.call_worker;
      case 'chat_with_worker':
        return loc.chat_with_worker;
      case 'select_worker':
        return loc.select_worker;
      case 'offer_price':
        return loc.offer_price;
      case 'reviews':
        return loc.reviews;
      case 'find_jobs':
        return loc.find_jobs;
      case 'wallet_balance':
        return loc.wallet_balance;
      case 'total_earnings':
        return loc.total_earnings;
      case 'jobs_done':
        return loc.jobs_done;
      case 'withdraw_btn':
        return loc.withdraw_btn;
      case 'active_jobs_title':
        return loc.active_jobs_title;
      case 'no_active_jobs':
        return loc.no_active_jobs;
      case 'no_active_jobs_sub':
        return loc.no_active_jobs_sub;
      case 'press_to_complete':
        return loc.press_to_complete;
      case 'complete_existing_job':
        return loc.complete_existing_job;
      case 'complete_existing_job_sub':
        return loc.complete_existing_job_sub;
      case 'return_to_job':
        return loc.return_to_job;
      case 'search_jobs_hint':
        return loc.search_jobs_hint;
      case 'no_jobs_found':
        return loc.no_jobs_found;
      case 'no_jobs_found_sub':
        return loc.no_jobs_found_sub;
      case 'new_tag':
        return loc.new_tag;
      case 'apply_btn':
        return loc.apply_btn;
      case 'worker_role':
        return loc.worker_role;
      case 'my_profile_menu':
        return loc.my_profile_menu;
      case 'settings_menu':
        return loc.settings_menu;
      case 'logout_menu':
        return loc.logout_menu;
      case 'job_description_title':
        return loc.job_description_title;
      case 'client_budget':
        return loc.client_budget;
      case 'client_label':
        return loc.client_label;
      case 'new_client_tag':
        return loc.new_client_tag;
      case 'bids_title':
        return loc.bids_title;
      case 'accept_btn':
        return loc.accept_btn;
      case 'decline_btn':
        return loc.decline_btn;
      case 'complete_job_code_btn':
        return loc.complete_job_code_btn;
      case 'ask_question_btn':
        return loc.ask_question_btn;
      case 'send_offer_btn':
        return loc.send_offer_btn;
      case 'ask_question_title':
        return loc.ask_question_title;
      case 'enter_message_hint':
        return loc.enter_message_hint;
      case 'cancel_btn':
        return loc.cancel_btn;
      case 'send_message_btn':
        return loc.send_message_btn;
      case 'send_offer_title':
        return loc.send_offer_title;
      case 'your_price_label':
        return loc.your_price_label;
      case 'message_to_client_label':
        return loc.message_to_client_label;
      case 'why_choose_you_hint':
        return loc.why_choose_you_hint;
      case 'submit_application_btn':
        return loc.submit_application_btn;
      case 'success_application_sent':
        return loc.success_application_sent;
      case 'job_accepted_success':
        return loc.job_accepted_success;
      case 'enter_completion_code':
        return loc.enter_completion_code;
      case 'verify_btn':
        return loc.verify_btn;
      case 'job_completed_success':
        return loc.job_completed_success;
      case 'completion_failed':
        return loc.completion_failed;
      case 'hello':
        return loc.hello;
      case 'loading':
        return loc.loading;
      case 'job_details':
        return loc.job_details;
      case 'congratulations':
        return loc.congratulations;
      case 'job_completed_content':
        return loc.job_completed_content;
      case 'you_earned':
        return loc.you_earned;
      case 'ok_btn':
        return loc.ok_btn;
      case 'active_job_title':
        return loc.active_job_title;
      case 'completion_request_hint':
        return loc.completion_request_hint;
      case 'service_label':
        return loc.service_label;
      case 'enter_completion_code_title':
        return loc.enter_completion_code_title;
      case 'chat_with_client_btn':
        return loc.chat_with_client_btn;
      case 'complete_job_button':
        return loc.complete_job_button;
      case 'success_message_sent':
        return loc.success_message_sent;
      case 'job_accept_failed':
        return loc.job_accept_failed;
      case 'complete_job_title':
        return loc.complete_job_title;
      case 'searching_messages':
        return loc.searching_messages;
      case 'no_messages_found':
        return loc.no_messages_found;
      case 'no_messages_found_sub':
        return loc.no_messages_found_sub;
      case 'failed_send_message':
        return loc.failed_send_message;
      case 'no_messages_yet_start':
        return loc.no_messages_yet_start;
      case 'rating_label':
        return loc.rating_label;
      case 'jobs_label':
        return loc.jobs_label;
      case 'completion_label':
        return loc.completion_label;
      case 'filter_active':
        return loc.filter_active;
      case 'filter_nearby':
        return loc.filter_nearby;
      case 'filter_high_pay':
        return loc.filter_high_pay;
      case 'terms_accept_label':
        return loc.terms_accept_label;
      case 'terms_link_text':
        return loc.terms_link_text;
      case 'terms_error':
        return loc.terms_error;
      case 'welcome_title_1':
        return loc.welcome_title_1;
      case 'welcome_subtitle_1':
        return loc.welcome_subtitle_1;
      case 'welcome_title_2':
        return loc.welcome_title_2;
      case 'welcome_subtitle_2':
        return loc.welcome_subtitle_2;
      case 'welcome_title_3':
        return loc.welcome_title_3;
      case 'welcome_subtitle_3':
        return loc.welcome_subtitle_3;
      case 'welcome_title_4':
        return loc.welcome_title_4;
      case 'welcome_subtitle_4':
        return loc.welcome_subtitle_4;
      case 'skip':
        return loc.skip;
      case 'start_now':
        return loc.start_now;
      case 'continue_btn':
        return loc.continue_btn;
      case 'have_account_login':
        return loc.have_account_login;
      case 'nyumbani_nav':
        return loc.nyumbani_nav;
      case 'kazi_zangu_nav':
        return loc.kazi_zangu_nav;
      case 'inbox_nav':
        return loc.inbox_nav;
      case 'wasifu_nav':
        return loc.wasifu_nav;
      case 'ask_worker_query':
        return loc.ask_worker_query;
      case 'search_hint':
        return loc.search_hint;
      case 'services_label':
        return loc.services_label;
      case 'nearby_workers_label':
        return loc.nearby_workers_label;
      case 'no_workers_nearby':
        return loc.no_workers_nearby;
      case 'failed_to_delete':
        return loc.failed_to_delete;
      case 'payment_retried':
        return loc.payment_retried;
      case 'no_jobs_posted_yet':
        return loc.no_jobs_posted_yet;
      case 'dash_nav':
        return loc.dash_nav;
      case 'feed_nav':
        return loc.feed_nav;
      case 'working_status':
        return loc.working_status;
      case 'active_job_label':
        return loc.active_job_label;
      case 'total_completed_jobs':
        return loc.total_completed_jobs;
      case 'your_rating':
        return loc.your_rating;
      case 'withdraw_money_btn':
        return loc.withdraw_money_btn;
      case 'no_active_job_msg':
        return loc.no_active_job_msg;
      case 'complete_current_job_first':
        return loc.complete_current_job_first;
      case 'cannot_see_new_jobs_msg':
        return loc.cannot_see_new_jobs_msg;
      case 'view_your_job_btn':
        return loc.view_your_job_btn;
      case 'job_market_label':
        return loc.job_market_label;
      case 'no_jobs_available':
        return loc.no_jobs_available;
      case 'try_again_later_msg':
        return loc.try_again_later_msg;
      case 'edit_profile_menu':
        return loc.edit_profile_menu;
      case 'job_history_menu':
        return loc.job_history_menu;
      case 'help_menu':
        return loc.help_menu;
      case 'worker_selected_success':
        return loc.worker_selected_success;
      case 'failed_fetch_job_details':
        return loc.failed_fetch_job_details;
      case 'apply_job_dialog_title':
        return loc.apply_job_dialog_title;
      case 'bid_hint':
        return loc.bid_hint;
      case 'posted_by_label':
        return loc.posted_by_label;
      case 'completion_code_label':
        return loc.completion_code_label;
      case 'no_desc':
        return loc.no_desc;
      case 'no_location':
        return loc.no_location;
      case 'applications_tab':
        return loc.applications_tab;
      case 'wallet_title':
        return loc.wallet_title;
      case 'deposit_btn':
        return loc.deposit_btn;
      case 'recent_transactions':
        return loc.recent_transactions;
      case 'no_transactions':
        return loc.no_transactions;
      case 'transaction':
        return loc.transaction;
      case 'verifying_code':
        return loc.verifying_code;
      case 'enter_code_error':
        return loc.enter_code_error;
      case 'status_label':
        return loc.status_label;
      case 'who_are_you':
        return loc.who_are_you;
      case 'role_muhitaji_title':
        return loc.role_muhitaji_title;
      case 'role_muhitaji_desc':
        return loc.role_muhitaji_desc;
      case 'role_mfanyakazi_title':
        return loc.role_mfanyakazi_title;
      case 'role_mfanyakazi_desc':
        return loc.role_mfanyakazi_desc;
      case 'withdraw_request_title':
        return loc.withdraw_request_title;
      case 'withdrawal_amount_label':
        return loc.withdrawal_amount_label;
      case 'amount_hint':
        return loc.amount_hint;
      case 'min_withdrawal_error':
        return loc.min_withdrawal_error;
      case 'insufficient_balance_error':
        return loc.insufficient_balance_error;
      case 'phone_networks_label':
        return loc.phone_networks_label;
      case 'submit_request_btn':
        return loc.submit_request_btn;
      case 'withdrawal_success_msg':
        return loc.withdrawal_success_msg;
      case 'status_open':
        return loc.status_open;
      case 'status_pending_applications':
        return loc.status_pending_applications;
      case 'retry_payment_btn':
        return loc.retry_payment_btn;
      default:
        return key;
    }
  }
}
